package xyz.block.bittycity.innie.models

import app.cash.kfsm.Value
import org.bitcoinj.base.Address
import org.joda.money.Money
import xyz.block.bittycity.common.models.Bitcoins
import xyz.block.bittycity.common.models.CustomerId
import xyz.block.bittycity.common.models.LedgerTransactionId
import xyz.block.bittycity.common.utils.CurrencyConversionUtils.bitcoinsToUsd
import java.time.Instant

data class Deposit(
  /** The deposit's unique token. */
  override val id: DepositToken,

  /** The time in epoch millis that this deposit was created. */
  val createdAt: Instant,

  /** The time in epoch millis that this deposit was updated. */
  val updatedAt: Instant,

  /** Each time the deposit's state is updated, the version increments. Zero-based. */
  val version: Long,

  /** The state of this deposit, in terms of the innie state machine. */
  override val state: DepositState,

  /** The ID of the customer receiving the deposit. */
  val customerId: CustomerId,

  /** The deposit amount, in bitcoins. */
  val amount: Bitcoins,

  /** The exchange rate used when creating the deposit. */
  val exchangeRate: Money? = null,

  /** The identifier of this deposit in the system that detects deposits in the blockchain. */
  val paymentToken: String,

  /** The blockchain transaction id hash for this deposit. */
  val blockchainTransactionId: String,

  /** The wallet address into which the deposit is sent. */
  val targetWalletAddress: Address,

  /** The ledger transaction id generated by the ledgering system. */
  val ledgerTransactionId: LedgerTransactionId? = null,

  /** The reason attributed to the failure of this deposit, if applicable. */
  val failureReason: DepositFailureReason? = null,

  /** If the deposit cannot be accepted then it has to be reversed. There can be multiple reversal attempts. */
  val reversals: List<DepositReversal> = emptyList(),
) : Value<DepositToken, Deposit, DepositState> {
  override fun update(newState: DepositState): Deposit = this.copy(state = newState)

  val fiatEquivalentAmount: Money? = this.amount.let { amount ->
    exchangeRate?.let { bitcoinsToUsd(amount, exchangeRate) }
  }
}
