package xyz.block.bittycity.innie.models

enum class DepositReversalFailureReason {
  UNKNOWN,
  CUSTOMER_CANCELLED,
  RISK_BLOCKED,
  STEP_UP_AUTHENTICATION_FAILED,
  SANCTIONS_DECLINED,
  SANCTIONS_FAILED,
  CUSTOMER_DECLINED_DUE_TO_SCAM_WARNING,
  ADMIN_FAILED,
  FAILED_ON_CHAIN,
  CUSTOMER_ABANDONED
}
