package xyz.block.bittycity.innie.models

enum class RequirementId(val requiresSecureEndpoint: Boolean) {
  DEPOSIT_CONFIRMED_ON_CHAIN(false),
  DEPOSIT_VOIDED(false),
  REVERSAL_TARGET_WALLET_ADDRESS(false),
  REVERSAL_SCAM_WARNING(false),
  REVERSAL_SCAM_WARNING_CANCELLED(false),
  REVERSAL_USER_CONFIRMATION(true),
  REVERSAL_SANCTIONS_WITHDRAWAL_REASON(true),
  REVERSAL_SANCTIONS_HELD(true),
  REVERSAL_OBSERVED_IN_MEMPOOL(true),
  REVERSAL_SELF_ATTESTATION(true),
  REVERSAL_SUBMITTED_ON_CHAIN(true),
  REVERSAL_FAILED_ON_CHAIN(true),
}
