CREATE TABLE withdrawals (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    token VARCHAR(128) NOT NULL,
    merchant_token VARCHAR(128) NOT NULL,
    source_balance_token VARCHAR(128) NOT NULL,
    state VARCHAR(64) NOT NULL,
    source varchar(64) NOT NULL DEFAULT 'BITTY',
    satoshis BIGINT UNSIGNED,
    usd_equivalent_cents BIGINT,
    target_wallet VARCHAR(128),
    block_target INT,
    fee BIGINT,
    ledger_entry_token VARCHAR(128),
    selected_speed VARCHAR(64),
    fee_margin INT,
    fiat_value_units BIGINT,
    fiat_value_currency VARCHAR(16),
    failure_reason VARCHAR(128),
    fee_flat_rate BIGINT,
    provider VARCHAR(64),
    blockchain_transaction_id VARCHAR(128),
    
    PRIMARY KEY (id),
    UNIQUE INDEX token_idx (token),
    UNIQUE INDEX merchant_token_idx (merchant_token),
    INDEX state_idx (state),
    INDEX ledger_entry_token_idx (ledger_entry_token)
); 
