package xyz.block.bittycity.outie.models

enum class FailureReason {
  UNKNOWN,
  CUSTOMER_CANCELLED,
  RISK_BLOCKED,
  LIMITED,
  STEP_UP_AUTHENTICATION_FAILED,
  SANCTIONS_DECLINED,
  SANCTIONS_FAILED,
  CUSTOMER_DECLINED_DUE_TO_SCAM_WARNING,
  INSUFFICIENT_FUNDS,
  CUSTOMER_IS_INELIGIBLE,
  ADMIN_FAILED,
  FAILED_ON_CHAIN,
  CUSTOMER_ABANDONED
}
